### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by Aholicknight**
This issue template will help the repo making the issues be more professional.

### CODE REVIEW

**Comment by mshar1** [comment]
If I want to encode the code to bypass the protections, where can I find the code in any file or class

**Comment by Aholicknight** [comment]
@mshar1 Why are you commenting on other people's issues? MAKE YOUR OWN ISSUE SO SOMEONE CAN HELP YOU INSTEAD OF COMMENTING ON SOMEONES ELSES.

**Comment by mshar1** [comment]
I apologize for you, I made a mistake in the response place

**Comment by mshar1** [comment]
I am sorry for you I made a mistake in the place of response

**Pull request closed without merging**
